clients/urls.py
from django.conf.urls import url

from . import views

app_name = 'clients'
urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^new/$', views.new, name='new'),
	url(r'^(?P<alias>[a-z0-9-]+)/$', views.client, name='client'),
]

kitchry/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('clients.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^clients/', include('clients.urls')),
]

clients/models.py
from django.db import models

# Create your models here.
class Client(models.Model):
	name = models.CharField(max_length=50)
	slug = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	email = models.CharField(max_length=50)
	profile_img = models.CharField(max_length=50)
	weight = models.FloatField(default=70.0)
	stats = models.CharField(max_length=200)
	
	def __str__(self):
		return self.stats

clients/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Client
import re
import random

# Create your views here.
def slugify(s):
	s = s.lower()

	for c in [' ', '-', '.', '/']:
		s = s.replace(c, '_')
	s = re.sub('\W', '', s)
	s = s.replace('_', ' ')
	s = re.sub('\s+', ' ', s)
	s = s.strip()
	s = s.replace(' ', '-')

	return s

def index(request):
	clients = Client.objects.all()
	return render(request,'clients/index.html',{'clients': clients})
	
def new(request):
	if(request.POST):
		s = slugify(request.POST['name'])
		if(_check(request.POST) == 1):
			return HttpResponse("Client with same name already exists!")
		elif(_check(request.POST) == 2):
			return HttpResponse("This email address already exists!")
		client = Client()
		client.name = request.POST['name']
		client.slug = s
		client.description = request.POST['description']
		client.email = request.POST['email']
		client.profile_img = request.POST['profile_img']
		client.weight = float(request.POST['weight'])
		client.stats = _stats(client.weight)		
		client.save()
		
		return HttpResponse("Client saved.")
	else:
		return render(request,'clients/new.html')
		
def client(request, alias):
	client = get_object_or_404(Client,slug = alias);
	if(request.POST):
		s = slugify(request.POST['name'])
		# if(_check(request.POST) == 1):
			# return HttpResponse("Client with same name already exists!")
		# elif(_check(request.POST) == 2):
			# return HttpResponse("This email address already exists!")		
		client.name = request.POST['name']
		client.slug = s
		client.description = request.POST['description']
		client.email = request.POST['email']
		client.profile_img = request.POST['profile_img']
		client.weight = float(request.POST['weight'])
		client.stats = _stats(client.weight)		
		client.save()
		
		return HttpResponseRedirect(reverse('clients:client', kwargs={'alias': s}))
	else:
		return render(request,'clients/client.html',{'client': client})
		
def _check(data):
	s = data['name']
	try:
		c = Client.objects.filter(name = s)
	except:
		c = None;
	if(c):
		return 1;
	s = slugify(data['name'])
	try:
		c = Client.objects.filter(slug = s)
	except:
		c = None;
	if(c):
		return 1;
		
	try:
		c = Client.objects.filter(email = data['email'])
	except:
		c = None;
	if(c):
		return 2;
		
def _stats(weight):
	w = []
	for x in range(52):
		w.append(round(random.uniform(weight - 10, weight + 10),1))
	ret = ',' . join(str(x) for x in w)
	return ret;

clients/templates/clients/client.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Client</title>
		<link rel="stylesheet" type="text/css" href='{% static "clients/style.css" %}'>
		<script src='{% static "clients/script.js" %}'></script>
		<script src='{% static "clients/canvasjs.min.js" %}'></script>
		<script type="text/javascript">
			window.onload = function () {
				var chartData = [{{ client.stats }}];
				var points = [];
				for(var i = 0; i < chartData.length; i ++) {
					var point = { x: i+1, y: chartData[i]};
					points.push(point);
				}
				var chart = new CanvasJS.Chart("chartContainer", {
					theme: "theme1",
					title: {
						text: "{{ client.name }} Weight Stats"
					},
					animationEnabled: true,
					axisX: {
						interval: 1,						

					},
					axisY: {
						includeZero: false

					},
					data: [{
						type: "line",
						//lineThickness: 3,
						dataPoints: points
					}
					]
				});

				chart.render();
			}
		</script>
	</head>
	<body>
		<h1>Client Profile</h1>
		<div class="client">
			<div class="profile">
				<img src='{% static "clients/images/avatar/" %}{{ client.profile_img }}' />
			</div>
			<div class="info">
				<h3>{{ client.name }}</h3>
				<p>{{ client.email }}</p>
			</div>
		</div>
		<div class="container">
		<br/>
			<form action="{% url 'clients:client' client.slug %}" method="POST">
			{% csrf_token %}
				<p><label for="name">Name :</label><input type="text" name="name" value='{{ client.name }}' /></p>
				<p><label for="email">Email :</label><input type="text" name="email" value='{{ client.email }}' /></p>
				<p><label for="description">Description :</label><input type="text" name="description" value='{{ client.description }}' /></p>
				<p><label for="profile_img">Profile Image :</label><input type="text" name="profile_img"  value='{{ client.profile_img }}' /></p>
				<p><label for="weight">Weight :</label><input type="text" name="weight" value='{{ client.weight }}' /></p>
				<p><input type="submit" value="Save" /></p>
			</form>
		</div>
		<div id="chartContainer" style="width: 90%; height: 500px;display: inline-block;"></div>
	</body>
</html>

clients/templates/clients/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Clients</title>
		<link rel="stylesheet" type="text/css" href='{% static "clients/style.css" %}'>
		<script src='{% static "clients/script.js" %}'></script>
	</head>
	<body>
		<h1>Clients listings</h1>
		<div class="createnew">
			<a href='{% url "clients:new" %}'>Create new user profile</a>
		</div>
		<div class="container">
		{% for client in clients %}
			<div class="client">
				<div class="profile">
					<img src='{% static "clients/images/avatar/" %}{{ client.profile_img }}' />
				</div>
				<div class="info">
					<h3><a href='{% url "clients:client" client.slug %}'>{{ client.name }}</a></h3>
					<p>{{ client.description }}</p>
				</div>
			</div>
		{% endfor %}
		</div>
	</body>
</html>

clients/templates/clients/new.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>New Client</title>
		<link rel="stylesheet" type="text/css" href='{% static "clients/style.css" %}'>
		<script src='{% static "clients/script.js" %}'></script>
	</head>
	<body>
		<h1>New Client</h1>		
		<div class="container">
		<br/>
			<form action="{% url 'clients:new' %}" method="POST">
			{% csrf_token %}
				<p><label for="name">Name :</label><input type="text" name="name"/></p>
				<p><label for="email">Email :</label><input type="text" name="email"/></p>
				<p><label for="description">Description :</label><input type="text" name="description"/></p>
				<p><label for="profile_img">Profile Image :</label><input type="text" name="profile_img" /></p>
				<p><label for="weight">Weight :</label><input type="text" name="weight" /></p>
				<p><input type="submit" value="Save" /></p>
			</form>
		</div>
	</body>
</html>